# Done to increase the memory available to gradle.
org.gradle.jvmargs=-Xmx1G
org.gradle.parallel=true

# Fabric Properties
# check these on https://fabricmc.net/develop
# do not change before updating mappings https://fabricmc.net/wiki/tutorial:migratemappings

# Checklist for up- / downgrading Minecraft version:
# - Upgrade Gradle wrapper
#	1. gradlew wrapper --gradle-version 8.14.3
#   2. gradlew --version
#   3. Clean / delete .gradle folder
# - Migrate mappings: https://fabricmc.net/develop/
#   - gradlew migrateMappings --mappings "1.21.4+build.8"
# - Move migrated source files into original source files
# - Update gradle.properties (this file): https://fabricmc.net/develop/
# - Update dependencies (Fabric API) fabric.mod.json
# - Clean directories / caches:
#   - .gradle/loom-cache
#   - .build/loom-cache
#   - .build/tmp
# - Generate sources
#   - gradlew genSources
#   - or gradlew genSourcesWithCfr
# - Download assets
#   - gradlew downloadAssets
# - Recreate launch configs
#   - gradlew vscode
# - Fix broken code
# - Refresh dependencies:
#   - gradlew build --refresh-dependencies
# - Build and debug mod
#   - Run first with gradlew runClient
# - Fix broken mixins

# In case VSCode launches client without mod installed:
#   - Verify game runs with when running client directly with gradle: `gradlew runClient`
#   - Delete .gradle folder

# In case imports cannot be resolved (Ctrl + Shift + P):
#   1. Java: Restart Java Language Server
#   2. or Java: Clean Java Language Server workspace
# https://wiki.fabricmc.net/documentation:fabric_loom
minecraft_version=1.21
yarn_mappings=1.21+build.9
loader_version=0.19.3
loom_version=1.17-SNAPSHOT

# Mod Properties
mod_version=0.1.1
mod_loader = fabric
maven_group=kirby144p.ssmc
archives_base_name=ssmc

# Dependencies
fabric_api_version=0.102.0+1.21