# Done to increase the memory available to gradle.
org.gradle.jvmargs=-Xmx1G
org.gradle.parallel=true

# Fabric Properties
# check these on https://fabricmc.net/develop
# do not change before updating mappings https://fabricmc.net/wiki/tutorial:migratemappings

# Checklist for upgrading Minecraft version:
# - Update/Upgrade gradle wrapper
#	--> e.g. gradlew wrapper --gradle-version 8.14.3
# - Migrate mappings: https://fabricmc.net/develop/
#   --> e.g. gradlew migrateMappings --mappings "1.21.4+build.8"
# - Move migrated source files into original source files
# - Update gradle.properties: https://fabricmc.net/develop/
# - Update fabric.mod.json
# - Generate sources
#   --> gradlew genSources
# - Download assets
#   --> gradlew downloadAssets
# - Fix broken code
# - Build and debug mod
# - Fix broken mixins

# In case imports cannot be resolved, clean the java language server workspace
# https://wiki.fabricmc.net/documentation:fabric_loom
minecraft_version=1.21.4
yarn_mappings=1.21.4+build.8
loader_version=0.19.3
loom_version=1.17-SNAPSHOT

# Mod Properties
mod_version=0.1.1
mod_loader = fabric
maven_group=kirby144p.ssmc
archives_base_name=ssmc

# Dependencies
fabric_api_version=0.119.4+1.21.4